{% set name = "pest-language-server" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pest-parser/pest-ide-tools/archive/v{{ version }}.tar.gz
  sha256: 6e3327c78b62aa12e4e2884449021e2915a97ccef36d1d907bbe669dbb1aaf5b

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - pest-language-server &  # [not win]
    - exe_pid=$!  # [not win]
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM  # [not win]
    - start /b pest-language-server   # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]
    - taskkill /F /im pest-language-server.exe  # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]

about:
  home: https://github.com/pest-parser/pest-ide-tools
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: IDE tools for writing pest grammars, using the Language Server Protocol for Visual Studio Code, Vim and other editors
  dev_url: https://github.com/pest-parser/pest-ide-tools

extra:
  recipe-maintainers:
    - danielnachun
